// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/13/2026, 8:12:50 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/brunotrinchao/Documentos/Bruno/Invoice-Track/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brunotrinchao/Documentos/Bruno/Invoice-Track/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brunotrinchao/Documentos/Bruno/Invoice-Track/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brunotrinchao/Documentos/Bruno/Invoice-Track/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brunotrinchao/Documentos/Bruno/Invoice-Track/app/plugins/**/*.{js,ts,mjs}","/home/brunotrinchao/Documentos/Bruno/Invoice-Track/app/composables/**/*.{js,ts,mjs}","/home/brunotrinchao/Documentos/Bruno/Invoice-Track/app/utils/**/*.{js,ts,mjs}","/home/brunotrinchao/Documentos/Bruno/Invoice-Track/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brunotrinchao/Documentos/Bruno/Invoice-Track/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/brunotrinchao/Documentos/Bruno/Invoice-Track/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/brunotrinchao/Documentos/Bruno/Invoice-Track/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;